name: Notify Server on Markdown Change

on:
  push:
    paths:
      - '**/*.md'  # Only trigger this workflow on Markdown file changes

jobs:
  notify_server:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Notify Server of Markdown Changes
      run: |
        # Your server URL
        SERVER_URL="https://localhost:7256/api/Git/Index"

        # Get the repository URL and branch
        REPO_URL="https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/"

        # Fetch all commits to ensure the diff command works
        git fetch --all

        # Get the list of modified Markdown files between HEAD and the base branch
        BASE_BRANCH="main"  # Change this to your base branch if necessary
        MODIFIED_FILES=$(git diff --name-only origin/${BASE_BRANCH} HEAD | grep '.md')

        # Read modified files
        for FILE in $MODIFIED_FILES; do
          # Construct file URL
          FILE_URL="${REPO_URL}${FILE}"

          # Send the URL to your server
          curl -X POST "$SERVER_URL" \
            -H "Content-Type: application/json" \
            -d "{\"fileUrl\": \"$FILE_URL\"}"

          echo "Sent URL to server: $FILE_URL"
        done
